module.exports = {
    pluginName: "homebridge-smartthings",
    platformDesc: "SmartThings",
    platformName: "SmartThings-v2",
    pluginVersion: require("../../package.json").version,
    packageFile: require("../../package.json"),
    knownCapabilities: [
        "Switch",
        "Light",
        "LightBulb",
        "Light Bulb",
        "Bulb",
        "Color Control",
        "Door",
        "Window",
        "Battery",
        "Polling",
        "Lock",
        "Refresh",
        "Lock Codes",
        "Sensor",
        "Actuator",
        "Configuration",
        "Switch Level",
        "Temperature Measurement",
        "Motion Sensor",
        "Color Temperature",
        "Illuminance Measurement",
        "Contact Sensor",
        "Acceleration Sensor",
        "Door Control",
        "Garage Door Control",
        "Relative Humidity Measurement",
        "Presence Sensor",
        "Carbon Dioxide Measurement",
        "Carbon Monoxide Detector",
        "Water Sensor",
        "Window Shade",
        "WindowShade",
        "Valve",
        "Energy Meter",
        "Power Meter",
        "Thermostat",
        "Thermostat Cooling Setpoint",
        "Thermostat Mode",
        "Thermostat Fan Mode",
        "Thermostat Operating State",
        "Thermostat Heating Setpoint",
        "Thermostat Setpoint",
        "Fan Speed",
        "Fan Control",
        "Fan Light",
        "Fan",
        "Speaker",
        "Tamper Alert",
        "Alarm",
        "Alarm System Status",
        "AlarmSystemStatus",
        "Mode",
        "Routine",
        "Button",
        // Sonos Capabilities
        "Audio Volume",
        "Audio Mute"
    ]
};